# Generated by Django 4.0 on 2021-12-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('home', models.CharField(max_length=33)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.CharField(max_length=500)),
                ('role', models.CharField(max_length=64)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='campaigns.campaign')),
            ],
        ),
    ]
