# Generated by Django 4.0 on 2021-12-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('registered', models.ManyToManyField(blank=True, related_name='employees', to='campaigns.Vacancy')),
            ],
        ),
    ]
